# Name of the workflow
name: Contribution Snake

# Triggers for the workflow
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }

# Jobs to be run in the workflow
jobs:
  # Name of the job
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Uses the Platane/snk action to generate a snake from your GitHub contributions
      - uses: Platane/snk@v3
        with:
          # The GitHub username to generate the snake for
          github_user_name: ${{ github.repository_owner }}
          # The output files to generate
          outputs: |
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake.svg
            ./assets/github-contribution-grid-snake-dark.svg?palette=github-dark
        # Environment variables available to the steps
        env:
          # The GitHub token used by the action to interact with the GitHub API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Uses the EndBug/add-and-commit action to commit the generated files to your repository
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          # The author of the commit
          default_author: github_actions
          # The commit message
          message: "Generate Contribution Snake - [Skip GitHub Action]"
